### ISSUE TITLE
demo 和 test 都无法通过

### ISSUE THREAD

**Issue by zhaomin94** [ascoders/dependency-inject#1]
![image](https://user-images.githubusercontent.com/20993820/48964160-7172e980-efdc-11e8-88e4-6d5134836a61.png)
将作者的库clone到本地，执行一系列初始化后，发现demo 和 test 都无法通过，大致信息如上截图，还望作者能够指点迷津。

**Comment by ascoders** [comment]
编译脚本过期了，通过换成我们统一维护的 [pri](https://github.com/prijs/pri) 解决了。
